### ISSUE TITLE
Timeouts - after 7pm every day??

### ISSUE THREAD

**Issue by mconlow** [scottbonline/sense#38]
Hi, I'm using the Sense Home Assistant integration, and I've noticed that every day at 7pm ET, my daily usage data goes to 0 and stay at 0 into the early mornings the next day before starting again. Link to image: https://ibb.co/wSWy6Lj

Today I used your wrapper to call the API directly, and this afternoon I was able to read my data, but this evening I'm getting timeouts from the API. Home Assistant likewise isn't getting updates, and I also can't access the Trends section in the Sense App.

So i guess the question is: are you aware of any rate-limiting in the Sense API? 

I don't see other Sense-HA people with this same problem, so any idea why I'd have this rate limiting issue but not others? 

Any help appreciated

**Comment by firestormo** [comment]
Sense has been having issues with their servers since yesterday 

> On Oct 27, 2020, at 6:35 PM, Mike Conlow <notifications@github.com> wrote:
> 
> ﻿
> Hi, I'm using the Sense Home Assistant integration, and I've noticed that every day at 7pm ET, my daily usage data goes to 0 and stay at 0 into the early mornings the next day before starting again. Link to image: https://ibb.co/wSWy6Lj
> 
> Today I used your wrapper to call the API directly, and this afternoon I was able to read my data, but this evening I'm getting timeouts from the API. Home Assistant likewise isn't getting updates, and I also can't access the Trends section in the Sense App.
> 
> So i guess the question is: are you aware of any rate-limiting in the Sense API?
> 
> I don't see other Sense-HA people with this same problem, so any idea why I'd have this rate limiting issue but not others?
> 
> Any help appreciated
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Confidentiality Notice: This e-mail and the information that it contains may be confidential, legally privileged and protected by law. Access by the intended recipient only is authorized. Any liability (in negligence or otherwise) arising from any third party acting, or refraining from acting, on any information contained in this e-mail is hereby excluded. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Copyright of this e-mail and attachments created by us belongs to Directgate.: the author also asserts the right to be identified as such and object to any misuse.

If you have received this e-mail in error, please notify us immediately by using the reply facility on your e-mail system.

If this message is being transmitted over the Internet, be aware that it may be intercepted by third parties. If you are not the intended recipient you may not use, disclose, distribute, copy, print or rely on this e-mail.

**Comment by mconlow** [comment]
I'm pretty sure my issue goes back before yesterday, but I'll wait until things are more stable and check again for sure. Thanks

**Comment by mconlow** [comment]
Things are lining up now, so I'm going to close this out for now. Will reopen it if I start seeing the same thing again. Thanks for responding quickly
